connection_string: DefaultEndpointsProtocol=https;AccountName=ifcb;AccountKey=mzeoQjV8g8RZyI18AdD4x1XxQRm0GesvssNtPgGNom7a8Kk3FRe8bjCm9BRq7m/gwqrK8GcwOXDBPKWq21jFPg==;EndpointSuffix=core.windows.net
image_container: naames
server: capstoneservercjault.database.windows.net
database: capstoneazure
db_user: CloudSA85da88d3
db_password: Passwordtest123