CREATE OR ALTER PROCEDURE GENERATE_IMAGES_TO_PREDICT
    @MODEL_ID INT
AS
BEGIN
    WITH EXISTING_IMAGES AS (
        SELECT DISTINCT I_ID
        FROM PREDICTIONS
        WHERE M_ID = @MODEL_ID
    )
    SELECT I.I_ID AS I_ID,
           I.FILEPATH AS BLOB_FILEPATH
    FROM IMAGES AS I
    LEFT JOIN EXISTING_IMAGES EI ON I.I_ID = EI.I_ID
    WHERE EI.I_ID IS NULL;
END;
