CREATE OR ALTER PROCEDURE AL_RANKINGS
    @MODEL_ID INT,
    @D_METRIC_ID INT,
    @RELABEL_LAMBDA FLOAT,
    @BATCH_SIZE INT
AS
BEGIN
    WITH LABEL_COUNTS AS (
        SELECT
            I_ID,
            SUM(WEIGHT) AS W_COUNT
        FROM LABELS
        GROUP BY I_ID
    )
    SELECT TOP (@BATCH_SIZE)
           I.I_ID AS IMAGE_ID,
           I.FILEPATH AS BLOB_FILEPATH,
           M.D_VALUE AS UNCERTAINTY,
           P.PRED_LABEL AS PRED_LABEL,
           P.CLASS_PROB AS PROBS,
           IIF(coalesce(L.W_COUNT, 0) < 10, (M.D_VALUE * EXP(-@RELABEL_LAMBDA * coalesce(L.W_COUNT, 0))), 0) AS RANK_SCORE
    FROM METRICS AS M
    INNER JOIN IMAGES AS I
        ON M.I_ID = I.I_ID
    INNER JOIN PREDICTIONS AS P
        ON M.I_ID = P.I_ID AND (M.M_ID = P.M_ID OR M.M_ID = 0) -- allow for test images that have M_ID=0
    LEFT JOIN LABEL_COUNTS AS L
        ON M.I_ID = L.I_ID
    WHERE
          P.M_ID = @MODEL_ID
      AND M.D_ID = @D_METRIC_ID
    ORDER BY RANK_SCORE DESC;
END;
