CREATE OR ALTER PROCEDURE AL_TRAIN_SET
    @MODEL_ID INT,
    @D_METRIC_ID INT,
    @TRAIN_SIZE INT,
    @MINIMUM_PERCENT FLOAT
AS
BEGIN
    WITH LABEL_COUNTS AS (
        SELECT I_ID,
               LABEL,
               SUM(WEIGHT) AS W_COUNT,
               SUM(WEIGHT) AS W_COUNT,
               SUM(SUM(WEIGHT)) OVER (PARTITION BY I_ID) AS TOTAL_SUM,
               CAST(SUM(WEIGHT) AS FLOAT) / (SUM(SUM(WEIGHT)) OVER (PARTITION BY I_ID)) as PERCENT_CONSENSUS,
        FROM LABELS
        GROUP BY I_ID, LABEL
    ),
    TEST_IMAGES AS (
        SELECT DISTINCT I_ID
        FROM METRICS
        WHERE D_ID = 0
    )
    SELECT I.I_ID AS IMAGE_ID,
           I.FILEPATH AS BLOB_FILEPATH,
           L.LABEL AS CONSENSUS,
--            L.LABEL_RANK AS LABEL_RANK,
--            L.PERCENT_CONSENSUS AS PERCENT_CONCENSUS,
           M.D_VALUE AS UNCERTAINTY
    FROM METRICS AS M
    INNER JOIN IMAGES AS I
        ON M.I_ID = I.I_ID
    INNER JOIN PREDICTIONS AS P
        ON M.I_ID = P.I_ID AND M.M_ID = P.M_ID
    INNER JOIN LABEL_COUNTS AS L
        ON M.I_ID = L.I_ID
    LEFT JOIN TEST_IMAGES AS TI
        ON M.I_ID = TI.I_ID
    WHERE TI.I_ID IS NULL
      AND M.M_ID = @MODEL_ID
      AND M.D_ID = @D_METRIC_ID
      AND L.LABEL_RANK = 1
      AND L.PERCENT_CONSENSUS > @MINIMUM_PERCENT
    ORDER BY UNCERTAINTY DESC;
END;