CREATE OR ALTER PROCEDURE AL_TRAIN_SET
    @MODEL_ID INT,
    @D_METRIC_ID INT,
    @TRAIN_SIZE INT
AS
BEGIN
    WITH LABEL_COUNTS AS (
        SELECT
            I_ID,
            SUM(WEIGHT) AS W_COUNT
        FROM LABELS
        GROUP BY I_ID
    )
    SELECT TOP (@TRAIN_SIZE)
           I.I_ID AS IMAGE_ID,
           I.FILEPATH AS BLOB_FILEPATH,
           D.D_VALUE AS UNCERTAINTY
    FROM METRICS AS M
    INNER JOIN IMAGES AS I
        ON M.I_ID = I.I_ID
    INNER JOIN PREDICTIONS AS P
        ON M.I_ID = P.I_ID AND M.M_ID = P.M_ID
    INNER JOIN LABEL_COUNTS AS L
        ON M.I_ID = L.I_ID
    WHERE
          M.M_ID = @MODEL_ID
      AND M.D_ID = @D_METRIC_ID
    ORDER BY UNCERTAINTY DESC;
END;