subscription_id: "156ffac2-0545-4d4e-aab3-f89b83635d04"
resource_group: "defaultresourcegroup-wus2"
workspace_name: "pivot"
experiment_name: "adt-pivot"
api_key: '4B2DTMyhNHgIk3lJtt8MSdBU5QodpCNf'

scoring_uri: "https://{endpoint_name}.westus2.inference.ml.azure.com/score"
cloud_url: "https://ifcb.blob.core.windows.net/naames/{filepath}"
